### ISSUE TITLE
Opaque struct type issue

### ISSUE THREAD

**Issue by manggoguy** [vaivaswatha/debugir#13]
Hi, I've been happy using this tool.

I found the error. Sometimes, some struct type are opaque like this
`%struct._IO_marker = type opaque`
If there is opaque struct type, we can see this sentence
"debugir: /home/mok/llvm/llvm-11.0.0.src/lib/IR/DataLayout.cpp:713: llvm::Align llvm::DataLayout::getAlignment(llvm::Type*, bool) const: Assertion `Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"' failed."
debugir should failed!

In DebugIR.cpp,  the problem occurs in function "DIType *getOrCreateType(Type *T)" 
At line 413, 

` DICompositeType *S = Builder.createStructType(
          LexicalBlockFileNode, ST->hasName()? T->getStructName():"literal", FileNode,
          /*LineNumber=*/0, Layout.getTypeSizeInBits(T),
          Layout.getABITypeAlignment(T), /*DIFlags=*/llvm::DINode::FlagZero,
          /*DerivedFrom=*/nullptr, llvm::DINodeArray()); // filled in later`
The problem occurs when calling "Layout.getTypeSizeInBits(T)"
I fix the only the line, but error occurs behind.

In my opinion, we should separate it into cases where the type is opaque and cases where it is not.
Do you have any idea?

Please check!

**Comment by manggoguy** [comment]
I tested the mcf in SPEC CPU2006, so i can't upload the file error occur.

**Comment by manggoguy** [comment]
I fix the problem adding the case of opaque struct type. 

If the type is opaque struct type, the code is below
`N=Builder.createUnspecifiedType(ST->getName();`

If you want, I'll do PR

**Comment by vaivaswatha** [comment]
> I fix the problem adding the case of opaque struct type.
> 
> If the type is opaque struct type, the code is below `N=Builder.createUnspecifiedType(ST->getName();`
> 
> If you want, I'll do PR

Thank you. Please create a PR.

**Comment by manggoguy** [comment]
#14
