### ISSUE TITLE
Struct Type name issue

### ISSUE THREAD

**Issue by manggoguy** [vaivaswatha/debugir#6]
Hi, I've been happy using this tool. 

I found the error. Sometimes, Structure type doesn't have no name because it is literal. 
If there is literal struct, we can see this sentence 
"debugir: IR/Type.cpp:587: llvm::StringRef llvm::StructType::getName() const: Assertion `!isLiteral() && "Literal structs never have names"' failed."
debugir should failed! 

In DebugIR.cpp, "std::string getTypeName(Type *T) " should be patched. 
Before T->getStructName() in the line 413, the below codes should be added

StructType* structType = dyn_cast<StructType>(T);
! structType->isLiteral() ? T->getStructName() : "Literal" 

And, the line 434  "(T->getStructName().str() + "." + std::to_string(tempNameCounter++))" should be patched below codes 
(!structType->isLiteral()?T->getStructName().str() + "." + std::to_string(tempNameCounter++):"literal")

If you want pull request, i will

Please check!

**Comment by vaivaswatha** [comment]
> Hi, I've been happy using this tool.
> 
> I found the error. Sometimes, Structure type doesn't have no name because it is literal. If there is literal struct, we can see this sentence "debugir: IR/Type.cpp:587: llvm::StringRef llvm::StructType::getName() const: Assertion `!isLiteral() && "Literal structs never have names"' failed." debugir should failed!
> 
> In DebugIR.cpp, "std::string getTypeName(Type *T) " should be patched. Before T->getStructName() in the line 413, the below codes should be added
> 
> StructType* structType = dyn_cast(T); ! structType->isLiteral() ? T->getStructName() : "Literal"
> 
> And, the line 434 "(T->getStructName().str() + "." + std::to_string(tempNameCounter++))" should be patched below codes (!structType->isLiteral()?T->getStructName().str() + "." + std::to_string(tempNameCounter++):"literal")
> 
> If you want pull request, i will
> 
> Please check!

Thank you for pointing this out. If you can create a PR that would be great !. Also if you have a small snippet which failed before but works after your patch, that would be helpful.

**Comment by manggoguy** [comment]
I used "Power" in Olden benchmark [https://github.com/compor/olden](url) and attached its bc file
[normal.bc.zip](https://github.com/vaivaswatha/debugir/files/9731100/normal.bc.zip)
I will create PR soon! Thanks!

**Comment by vaivaswatha** [comment]
Closed by #7
